/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    usuarios: UsuarioAuthOperations;
  };
  blocks: {};
  collections: {
    usuarios: Usuario;
    media: Media;
    categorias: Categoria;
    marcas: Marca;
    productos: Producto;
    clientes: Cliente;
    ordenes: Ordene;
    cupones: Cupone;
    envios: Envio;
    suscriptores: Suscriptore;
    banners: Banner;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    usuarios: UsuariosSelect<false> | UsuariosSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categorias: CategoriasSelect<false> | CategoriasSelect<true>;
    marcas: MarcasSelect<false> | MarcasSelect<true>;
    productos: ProductosSelect<false> | ProductosSelect<true>;
    clientes: ClientesSelect<false> | ClientesSelect<true>;
    ordenes: OrdenesSelect<false> | OrdenesSelect<true>;
    cupones: CuponesSelect<false> | CuponesSelect<true>;
    envios: EnviosSelect<false> | EnviosSelect<true>;
    suscriptores: SuscriptoresSelect<false> | SuscriptoresSelect<true>;
    banners: BannersSelect<false> | BannersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'config-tienda': ConfigTienda;
  };
  globalsSelect: {
    'config-tienda': ConfigTiendaSelect<false> | ConfigTiendaSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: Usuario;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UsuarioAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios".
 */
export interface Usuario {
  id: number;
  nombre: string;
  rol?: ('admin' | 'editor' | 'vendedor') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'usuarios';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    banner?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias".
 */
export interface Categoria {
  id: number;
  nombre: string;
  /**
   * Ej: zapatillas-running (sin espacios, en minusculas)
   */
  slug: string;
  descripcion?: string | null;
  imagen?: (number | null) | Media;
  /**
   * Ej: teni, running, futbol
   */
  icono?: string | null;
  /**
   * Deja vacio si es categoria principal
   */
  categoriaPadre?: (number | null) | Categoria;
  orden?: number | null;
  activa?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marcas".
 */
export interface Marca {
  id: number;
  nombre: string;
  slug: string;
  logo?: (number | null) | Media;
  activa?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productos".
 */
export interface Producto {
  id: number;
  nombre: string;
  /**
   * Ej: air-max-270-negro (sin espacios)
   */
  slug: string;
  descripcion?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  sku?: string | null;
  precio: number;
  /**
   * Dejar vacio si no hay descuento
   */
  precioAnterior?: number | null;
  categoria: number | Categoria;
  marca?: (number | null) | Marca;
  /**
   * Color del producto (las variantes de talla heredan este color). Ej: Negro / Blanco
   */
  color?: string | null;
  /**
   * Permite filtrar el catalogo por publico objetivo.
   */
  segmento?: ('hombre' | 'mujer' | 'ninos' | 'unisex') | null;
  imagenPrincipal?: (number | null) | Media;
  imagenes?:
    | {
        imagen: number | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Interruptor maestro de compra. Si esta apagado, la ficha solo muestra consulta por WhatsApp. Encender unicamente cuando el stock por talla este verificado.
   */
  ventaOnline?: boolean | null;
  /**
   * Los rangos historicos (ej: "36 al 40") NO son vendibles online: sirven solo como referencia de consulta. Para vender online, registra tallas individuales con stock real y marca "Vendible online" en cada una.
   */
  tallas?:
    | {
        /**
         * Talla individual. Ej: 38, 39, S, M, L
         */
        talla: string;
        stock: number;
        /**
         * Solo tallas individuales con stock verificado.
         */
        ventaHabilitada?: boolean | null;
        skuVariante?: string | null;
        /**
         * Dejar vacio para usar el precio del producto.
         */
        precio?: number | null;
        imagen?: (number | null) | Media;
        id?: string | null;
      }[]
    | null;
  /**
   * Solo si el producto no tiene tallas
   */
  stock?: number | null;
  etiqueta?: ('' | 'nuevo' | 'hot' | 'top' | 'oferta') | null;
  destacado?: boolean | null;
  nuevoIngreso?: boolean | null;
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes".
 */
export interface Cliente {
  id: number;
  nombre: string;
  telefono?: string | null;
  email?: string | null;
  documento?: string | null;
  direccion?: {
    calle?: string | null;
    distrito?: string | null;
    ciudad?: string | null;
    referencias?: string | null;
  };
  /**
   * Notas privadas sobre el cliente (no las ve el cliente)
   */
  notas?: string | null;
  totalCompras?: number | null;
  etiqueta?: ('normal' | 'vip' | 'frecuente' | 'inactivo') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ordenes".
 */
export interface Ordene {
  id: number;
  numeroPedido?: string | null;
  /**
   * Se usa para correlacion con pasarela de pago
   */
  codigoCorrelacion?: string | null;
  cliente?: (number | null) | Cliente;
  /**
   * Snapshot al momento de crear la orden
   */
  nombreCliente: string;
  telefono: string;
  metodoEntrega: 'delivery' | 'retiro_tienda';
  items: {
    producto: number | Producto;
    nombreProducto: string;
    talla?: string | null;
    cantidad: number;
    precioUnitario: number;
    subtotal: number;
    id?: string | null;
  }[];
  subtotal?: number | null;
  descuento?: number | null;
  costoEnvio?: number | null;
  total?: number | null;
  cupon?: (number | null) | Cupone;
  direccionEnvio: {
    calle: string;
    distrito: string;
    ciudad?: string | null;
    referencias?: string | null;
  };
  metodoPago?: ('yape' | 'plin' | 'interbank' | 'transferencia' | 'tarjeta' | 'efectivo' | 'whatsapp') | null;
  estadoComercial: 'pendiente' | 'procesando' | 'enviado' | 'entregado' | 'cancelado';
  estadoPago: 'pending' | 'authorized' | 'paid' | 'failed' | 'canceled' | 'refunded';
  /**
   * manual, izipay, etc.
   */
  paymentProvider?: string | null;
  /**
   * Codigo tecnico del metodo de pago
   */
  paymentMethod?: string | null;
  transactionId?: string | null;
  externalOrderId?: string | null;
  paymentReference?: string | null;
  authorizationCode?: string | null;
  paymentPayload?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  paymentSignatureValid?: boolean | null;
  paidAt?: string | null;
  paymentErrorCode?: string | null;
  paymentErrorMessage?: string | null;
  notas?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cupones".
 */
export interface Cupone {
  id: number;
  /**
   * Ej: VERANO20, NIKE10OFF
   */
  codigo: string;
  tipo: 'porcentaje' | 'monto' | 'envio_gratis';
  /**
   * Ej: 20 = 20% o S/20 según el tipo
   */
  valor?: number | null;
  minimoCompra?: number | null;
  /**
   * Dejar en 0 para ilimitado
   */
  usoMaximo?: number | null;
  usosActuales?: number | null;
  /**
   * Dejar vacío para sin vencimiento
   */
  vencimiento?: string | null;
  activo?: boolean | null;
  descripcion?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "envios".
 */
export interface Envio {
  id: number;
  /**
   * Ej: Lima Metropolitana, Provincias, Envío Express
   */
  nombre: string;
  /**
   * Ej: Entrega en 24-48 horas
   */
  descripcion?: string | null;
  costo: number;
  /**
   * Ej: 1-2 días
   */
  tiempoEntrega?: string | null;
  /**
   * Dejar en 0 si no aplica envío gratis
   */
  minimoGratis?: number | null;
  distritos?:
    | {
        distrito: string;
        id?: string | null;
      }[]
    | null;
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suscriptores".
 */
export interface Suscriptore {
  id: number;
  telefono: string;
  /**
   * Marca aquí cuando ya le hayas escrito.
   */
  contactado?: boolean | null;
  /**
   * Ej: Le interesa running, esperando respuesta...
   */
  nota?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners".
 */
export interface Banner {
  id: number;
  titulo: string;
  subtitulo?: string | null;
  descripcion?: string | null;
  imagen?: (number | null) | Media;
  /**
   * Ej: #1a237e
   */
  colorFondo?: string | null;
  textBoton1?: string | null;
  urlBoton1?: string | null;
  textBoton2?: string | null;
  urlBoton2?: string | null;
  orden?: number | null;
  activo?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'usuarios';
        value: number | Usuario;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'categorias';
        value: number | Categoria;
      } | null)
    | ({
        relationTo: 'marcas';
        value: number | Marca;
      } | null)
    | ({
        relationTo: 'productos';
        value: number | Producto;
      } | null)
    | ({
        relationTo: 'clientes';
        value: number | Cliente;
      } | null)
    | ({
        relationTo: 'ordenes';
        value: number | Ordene;
      } | null)
    | ({
        relationTo: 'cupones';
        value: number | Cupone;
      } | null)
    | ({
        relationTo: 'envios';
        value: number | Envio;
      } | null)
    | ({
        relationTo: 'suscriptores';
        value: number | Suscriptore;
      } | null)
    | ({
        relationTo: 'banners';
        value: number | Banner;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'usuarios';
    value: number | Usuario;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "usuarios_select".
 */
export interface UsuariosSelect<T extends boolean = true> {
  nombre?: T;
  rol?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        banner?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categorias_select".
 */
export interface CategoriasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  descripcion?: T;
  imagen?: T;
  icono?: T;
  categoriaPadre?: T;
  orden?: T;
  activa?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "marcas_select".
 */
export interface MarcasSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  logo?: T;
  activa?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "productos_select".
 */
export interface ProductosSelect<T extends boolean = true> {
  nombre?: T;
  slug?: T;
  descripcion?: T;
  sku?: T;
  precio?: T;
  precioAnterior?: T;
  categoria?: T;
  marca?: T;
  color?: T;
  segmento?: T;
  imagenPrincipal?: T;
  imagenes?:
    | T
    | {
        imagen?: T;
        id?: T;
      };
  ventaOnline?: T;
  tallas?:
    | T
    | {
        talla?: T;
        stock?: T;
        ventaHabilitada?: T;
        skuVariante?: T;
        precio?: T;
        imagen?: T;
        id?: T;
      };
  stock?: T;
  etiqueta?: T;
  destacado?: T;
  nuevoIngreso?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clientes_select".
 */
export interface ClientesSelect<T extends boolean = true> {
  nombre?: T;
  telefono?: T;
  email?: T;
  documento?: T;
  direccion?:
    | T
    | {
        calle?: T;
        distrito?: T;
        ciudad?: T;
        referencias?: T;
      };
  notas?: T;
  totalCompras?: T;
  etiqueta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ordenes_select".
 */
export interface OrdenesSelect<T extends boolean = true> {
  numeroPedido?: T;
  codigoCorrelacion?: T;
  cliente?: T;
  nombreCliente?: T;
  telefono?: T;
  metodoEntrega?: T;
  items?:
    | T
    | {
        producto?: T;
        nombreProducto?: T;
        talla?: T;
        cantidad?: T;
        precioUnitario?: T;
        subtotal?: T;
        id?: T;
      };
  subtotal?: T;
  descuento?: T;
  costoEnvio?: T;
  total?: T;
  cupon?: T;
  direccionEnvio?:
    | T
    | {
        calle?: T;
        distrito?: T;
        ciudad?: T;
        referencias?: T;
      };
  metodoPago?: T;
  estadoComercial?: T;
  estadoPago?: T;
  paymentProvider?: T;
  paymentMethod?: T;
  transactionId?: T;
  externalOrderId?: T;
  paymentReference?: T;
  authorizationCode?: T;
  paymentPayload?: T;
  paymentSignatureValid?: T;
  paidAt?: T;
  paymentErrorCode?: T;
  paymentErrorMessage?: T;
  notas?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cupones_select".
 */
export interface CuponesSelect<T extends boolean = true> {
  codigo?: T;
  tipo?: T;
  valor?: T;
  minimoCompra?: T;
  usoMaximo?: T;
  usosActuales?: T;
  vencimiento?: T;
  activo?: T;
  descripcion?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "envios_select".
 */
export interface EnviosSelect<T extends boolean = true> {
  nombre?: T;
  descripcion?: T;
  costo?: T;
  tiempoEntrega?: T;
  minimoGratis?: T;
  distritos?:
    | T
    | {
        distrito?: T;
        id?: T;
      };
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "suscriptores_select".
 */
export interface SuscriptoresSelect<T extends boolean = true> {
  telefono?: T;
  contactado?: T;
  nota?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "banners_select".
 */
export interface BannersSelect<T extends boolean = true> {
  titulo?: T;
  subtitulo?: T;
  descripcion?: T;
  imagen?: T;
  colorFondo?: T;
  textBoton1?: T;
  urlBoton1?: T;
  textBoton2?: T;
  urlBoton2?: T;
  orden?: T;
  activo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "config-tienda".
 */
export interface ConfigTienda {
  id: number;
  nombreTienda: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  colores?: {
    primario?: string | null;
    acento?: string | null;
    fondo?: string | null;
  };
  moneda?: {
    simbolo?: string | null;
    codigoISO?: string | null;
  };
  header?: {
    anuncioBarra?: string | null;
    mostrarAnuncio?: boolean | null;
    textoBtnWhatsapp?: string | null;
    numeroWhatsapp?: string | null;
    menuPrincipal?:
      | {
          etiqueta: string;
          url: string;
          esDestacado?: boolean | null;
          subItems?:
            | {
                etiqueta: string;
                url: string;
                id?: string | null;
              }[]
            | null;
          id?: string | null;
        }[]
      | null;
  };
  home?: {
    secciones?:
      | {
          key: 'categorias' | 'marcas' | 'destacados' | 'suscripcion';
          orden?: number | null;
          mostrar?: boolean | null;
          titulo: string;
          subtitulo?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  footer?: {
    descripcion?: string | null;
    telefono?: string | null;
    email?: string | null;
    direccion?: string | null;
    horario?: string | null;
    redesSociales?: {
      facebook?: string | null;
      instagram?: string | null;
      tiktok?: string | null;
      youtube?: string | null;
    };
    linksRapidos?:
      | {
          etiqueta: string;
          url: string;
          id?: string | null;
        }[]
      | null;
    textoCopyright?: string | null;
  };
  pagos?: {
    metodos?:
      | {
          nombre: string;
          codigo?: ('yape' | 'plin' | 'interbank' | 'transferencia' | 'tarjeta' | 'efectivo' | 'whatsapp') | null;
          activo?: boolean | null;
          mostrarEnFooter?: boolean | null;
          instruccion?: string | null;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    metaTitulo?: string | null;
    metaDescripcion?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "config-tienda_select".
 */
export interface ConfigTiendaSelect<T extends boolean = true> {
  nombreTienda?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  colores?:
    | T
    | {
        primario?: T;
        acento?: T;
        fondo?: T;
      };
  moneda?:
    | T
    | {
        simbolo?: T;
        codigoISO?: T;
      };
  header?:
    | T
    | {
        anuncioBarra?: T;
        mostrarAnuncio?: T;
        textoBtnWhatsapp?: T;
        numeroWhatsapp?: T;
        menuPrincipal?:
          | T
          | {
              etiqueta?: T;
              url?: T;
              esDestacado?: T;
              subItems?:
                | T
                | {
                    etiqueta?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
            };
      };
  home?:
    | T
    | {
        secciones?:
          | T
          | {
              key?: T;
              orden?: T;
              mostrar?: T;
              titulo?: T;
              subtitulo?: T;
              id?: T;
            };
      };
  footer?:
    | T
    | {
        descripcion?: T;
        telefono?: T;
        email?: T;
        direccion?: T;
        horario?: T;
        redesSociales?:
          | T
          | {
              facebook?: T;
              instagram?: T;
              tiktok?: T;
              youtube?: T;
            };
        linksRapidos?:
          | T
          | {
              etiqueta?: T;
              url?: T;
              id?: T;
            };
        textoCopyright?: T;
      };
  pagos?:
    | T
    | {
        metodos?:
          | T
          | {
              nombre?: T;
              codigo?: T;
              activo?: T;
              mostrarEnFooter?: T;
              instruccion?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitulo?: T;
        metaDescripcion?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}